### PR TITLE
Make process_request return a response

### PR DESCRIPTION
**Pull request by ianzapolsky**
See #7 for more context.

### CODE REVIEW

**Comment by ianzapolsky** [comment]
See #7 for more context.

**Comment by ianzapolsky** [comment]
As an aside, the pipeline looks broken on python versioning issue..
```
py34 create: /home/travis/build/23andMe/djdt-flamegraph/.tox/py34
ERROR: InterpreterNotFound: python3.4
___________________________________ summary ____________________________________
  py27: commands succeeded
ERROR:  py34: InterpreterNotFound: python3.4
The command "tox" exited with 1.
```

**Comment by ianzapolsky** [comment]
Hey @blopker, is there any way you can share some info on the state of this repo's build situation?

**Comment by blopker** [comment]
Hey @ianzapolsky, we don't really run this internally anymore, but let me merge this and see if I can get the pipeline working again.

**Comment by blopker** [comment]
OK, working again. If you rebase you should be green.

**Comment by ianzapolsky** [comment]
@blopker Thanks for jumping on this - figured with the activity in this repo that it hasn't seen a lot of use lately. I've rebased my branch - hopefully this will get the project on track for more recent versions of DJDT.

Just out of curiosity - are you using something else to profile your Django apps nowadays?

**Comment by blopker** [comment]
Good question. While I think this tool is still useful for smaller projects, the single threaded requirement makes it hard to use on our larger projects. Instead, we've developed our own custom debug panels that hook into our other custom code for more specific instrumentation. These tools wouldn't be much use to anyone else though. 

However, I've had some good success running https://github.com/benfred/py-spy on general Python apps and I can't vouch for it, but https://github.com/emeryberger/scalene also looks interesting.

**Pull request merged**
